### ISSUE TITLE
How do you know what version is running?

### ISSUE THREAD

**Issue by lanhampr** [SonarSoftwareInc/poller#16]
How do you know what version is running? Also, how do you upgrade?

**Comment by schneis** [comment]
Excellent questions ... would be nice if Sonar would respond ...

**Comment by LarrySonar** [comment]
There was a bug in the code for 2.0.13 that will be fixed in a release coming very soon.  It will be displayed prominently on the Home page as shown below:

![image](https://user-images.githubusercontent.com/109091854/214842716-eb736391-96d9-46a6-8b5e-30d785da559a.png)

**Comment by LarrySonar** [comment]
Version 2.0.14 has been released which should address this issue.

**Comment by schneis** [comment]
@LarrySonar ... You did not respond to the original question on how to upgrade the poller.

**Comment by LarrySonar** [comment]
Sorry about that, the poller is self updating.  During the setup a cron job is created that once per day checks (assuming it has Internet connectivity) if there are updates and applies them / restarts as needed.  If you would for some reason want to trigger this process manually the upgrade script is located at:
`/usr/share/sonar_poller/upgrade.sh`
It must be run using sudo or as the root user.  You must also be able to reach this repository from that machine.  Hope this helps.

**Comment by schneis** [comment]
@LarrySonar - Thank you.  Please add this to the Readme that is displayed for the project so that it is documented?

**Comment by lanhampr** [comment]
When I try and upgrade I get:

fatal: detected dubious ownership in repository at '/usr/share/sonar_poller'
To add an exception for this directory, call:

	git config --global --add safe.directory /usr/share/sonar_poller

I am very green with how git works.

**Comment by lanhampr** [comment]
Nevermind, I changed to root then ran the script. All good.
