### ISSUE TITLE
Installation fails on new ubuntu server 20.04.5 VM

### ISSUE THREAD

**Issue by schneis** [SonarSoftwareInc/poller#17]
Setup a new VM using the ubuntu-20.04.5-live-server-amd64.iso.

Installed the poller using provided instructions:
```
wget https://raw.githubusercontent.com/SonarSoftwareInc/poller/master/setup.sh
chmod +x setup.sh
sudo ./setup.sh
```

Had the installer require generation of a GitHub token to be able to install the Composer?
```
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+sonar-poller+2023-01-13+1438
to retrieve a token. It will be stored in "{path}/.composer/auth.json" for future use by Composer.
Token (hidden): 
```

Saw these messages indicating an error just before the setup rebooted the VM to complete the installation:
```
In JsonConfigSource.php line 243:
                                                                                                          
  file_put_contents({path}/.composer/auth.json): failed to open stream: No such file or directory  
                                                                                                          

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>...]

```

After the VM reboots, I open a web-browser to the VM's IP address, after being redirected to the SSL URL the browser shows a "HTTP ERROR 500".
Looking in /var/log/nginx/error.log, I see this error logged:
`2023/01/13 14:49:06 [error] 613#613: *8 FastCGI sent in stderr: "PHP message: PHP Warning:  require(/usr/share/sonar_poller/www/../vendor/autoload.php): failed to open stream: No such file or directory in /usr/share/sonar_poller/www/index.php on line 3PHP message: PHP Fatal error:  require(): Failed opening required '/usr/share/sonar_poller/www/../vendor/autoload.php' (include_path='.:/usr/share/php') in /usr/share/sonar_poller/www/index.php on line 3" while reading response header from upstream, client: {IP}, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "{IP}"
`

**Please provide a working install script.**

**Comment by LarrySonar** [comment]
Stuart,
Have you been able to resolve this?  I fired up a fresh VM with the same ISO and following the installation / reboot logged in and ran the three setup commands you reference above.  It ran through the setup script and rebooted as expected.  Once rebooted the web interface was accessible.

The setup.sh should not have ever asked you to setup an access token which is where things seem to have failed.  If possible please create a new fresh VM and try again.  If the problem persists you can contact Sonar support for further assistance.  Thanks!

**Comment by schneis** [comment]
@LarrySonar I reached out to Sonar Support when there was no response here ... they were able to duplicate the issue and the devs are supposed to be working on it.

(Ticket # 52341)

**Comment by LarrySonar** [comment]
Support was able to work with customer and get this installed on a fresh VM using the provided instructions.
